language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install -q --use-mirrors Mercurial${HG_VERSION+==$HG_VERSION} || true
  - pip install -q --use-mirrors bzr${BZR_VERSION+==$BZR_VERSION} || true
  - pip install -q --use-mirrors hg-git || true

script:
  - hg --version || true
  - bzr --version || true
  - export GIT_TEST_OPTS='-v'
  - export PYTHON_PATH="$(which python)"
  - make
  - make -C contrib/remote-helpers

matrix:
  include:
    - python: 2.7
      env: BZR_VERSION=2.6b2
    - python: 2.7
      env: BZR_VERSION=2.5.1
    - python: 2.7
      env: BZR_VERSION=2.2.3
    - python: 2.7
      env: HG_VERSION=2.6.1
    - python: 2.7
      env: HG_VERSION=2.4
    - python: 2.7
      env: HG_VERSION=2.2
    - python: 2.7
      env: HG_VERSION=2.0
    - python: 2.7
      env: HG_VERSION=1.9.3
